#!/bin/bash

# Install the Fasttrack Archive Keyring
if ! apt-get -y install gpg fasttrack-archive-keyring; then
    echo "Failed to install fasttrack-archive-keyring"
    exit 1
fi

# Add VirtualBox repo and key
wget -O- -q https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmour -o /usr/share/keyrings/oracle_vbox_2016.gpg

# Define the path to the sources.list file
SOURCE_LIST="/etc/apt/sources.list"

# Remove the existing sources.list file if it exists
if [ -f "$SOURCE_LIST" ]; then
    rm -f "$SOURCE_LIST"
fi

# Create sources.list
cat <<EOL > "$SOURCE_LIST"
deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-fasttrack main contrib non-free
deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-backports-staging main contrib non-free
deb https://ftp.debian.org/debian/ bookworm contrib main non-free non-free-firmware
deb https://ftp.debian.org/debian/ bookworm-updates contrib main non-free non-free-firmware
deb https://ftp.debian.org/debian/ bookworm-proposed-updates contrib main non-free non-free-firmware
deb https://ftp.debian.org/debian/ bookworm-backports contrib main non-free non-free-firmware
deb https://deb.debian.org/debian-security bookworm-security contrib main non-free-firmware
deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox_2016.gpg] http://download.virtualbox.org/virtualbox/debian bookworm contrib
deb https://repository.spotify.com stable non-free
EOL

# Update package lists
apt-get update

echo "Done"
